# Gauss Elimination

this notebook goes through the process of implementing a simple Gaussian Elimination routine to solve a set of linear equations

$$
\mathbf{A}\mathbf{x} = \mathbf{b}
$$

accompanies the lecture at
https://mattatlincoln.github.io/teaching/numerical_methods/lecture_2/#/

In [1]:
# use numpy library and shorted its name in this workbook to np
import numpy as np

In [2]:
# setup an augmented matrix to represent our set of linear equations
dimension = 4
matdim = (dimension, dimension+1)
augmat = np.zeros(matdim)

In [3]:
augmat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

For now we will just fill in the required entries by hand. Make sure you are ok with the indexing.
We will use the example in the lecture
https://mattatlincoln.github.io/teaching/numerical_methods/lecture_2/#/2

In [24]:
# first row
augmat[0,0] = 2
augmat[0,1] = 2
augmat[0,2] = 4
augmat [0,3] = -2
augmat [0,4] = 10.0

In [25]:
# second row
augmat[1,0] = 1
augmat[1,1] = 3
augmat[1,2] = 2
augmat [1,3] = 4
augmat [1,4] = 17.0

In [26]:
# third row
augmat[2,0] = 3
augmat[2,1] = 1
augmat[2,2] = 3
augmat [2,3] = 1
augmat [2,4] = 18.0

In [27]:
# fourth row
augmat[3,0] = 1
augmat[3,1] = 3
augmat[3,2] = 4
augmat[3,3] = 2
augmat[3,4] = 27.0

In [28]:
# check we've got it right
augmat

array([[ 2.,  2.,  4., -2., 10.],
       [ 1.,  3.,  2.,  4., 17.],
       [ 3.,  1.,  3.,  1., 18.],
       [ 1.,  3.,  4.,  2., 27.]])

## pen and paper gauss elim

first row - so row with i = 0 

In [29]:
# 2nd row i.e pivot row + 1
# we need augmat[1,0] to be set to zero after this operation

In [30]:
refrow = 0
for row in range(refrow+1, dimension):
    print(row)
    ratio =  augmat[row,0]/augmat[refrow,0]
    for col in range(0, dimension+1):
        augmat[row,col] = augmat[row,col] - augmat[refrow,col]*ratio

#  old code replaced by 2nd loop
#        augmat[row,1] = augmat[row,1] - augmat[refrow,1]*ratio
#        augmat[row,2] = augmat[row,2] - augmat[refrow,2]*ratio
#        augmat[row,3] = augmat[row,3] - augmat[refrow,3]*ratio
#        augmat[row,4] = augmat[row,4] - augmat[refrow,4]*ratio

1
2
3


In [31]:
augmat

array([[ 2.,  2.,  4., -2., 10.],
       [ 0.,  2.,  0.,  5., 12.],
       [ 0., -2., -3.,  4.,  3.],
       [ 0.,  2.,  2.,  3., 22.]])

In [32]:
# now do the 2nd row

In [33]:
refrow = 1
for row in range(refrow+1, dimension):
    print(row)
    ratio =  augmat[row,refrow]/augmat[refrow,refrow]
    for col in range(refrow, dimension+1):
        augmat[row,col] = augmat[row,col] - augmat[refrow,col]*ratio

2
3


In [34]:
augmat

array([[ 2.,  2.,  4., -2., 10.],
       [ 0.,  2.,  0.,  5., 12.],
       [ 0.,  0., -3.,  9., 15.],
       [ 0.,  0.,  2., -2., 10.]])

In [35]:
refrow = 2
for row in range(refrow+1, dimension):
    print(row)
    ratio =  augmat[row,refrow]/augmat[refrow,refrow]
    for col in range(refrow, dimension+1):
        augmat[row,col] = augmat[row,col] - augmat[refrow,col]*ratio

3


In [36]:
augmat

array([[ 2.,  2.,  4., -2., 10.],
       [ 0.,  2.,  0.,  5., 12.],
       [ 0.,  0., -3.,  9., 15.],
       [ 0.,  0.,  0.,  4., 20.]])

but notice that the last few cells are identical except the refrow value increasing. They can be replaced be another loop!

## Back substitution

now we need to get the actual solution vector working backwards through our triangularised set of equations

In [42]:
# create a solution vector
x = np.zeros(dimension)

# first equation
row = dimension-1
x[row] = augmat[row, dimension]/augmat[row, dimension-1]

In [43]:
x

array([0., 0., 0., 5.])

In [45]:
# 2nd equation - we want to subtract the bits we know from prevous x values then solve
row = dimension - 2
x[row] = (augmat[row,dimension] 
          -augmat[row,dimension-1]*x[dimension-1])/augmat[row, dimension-2]

In [46]:
x

array([ 0.,  0., 10.,  5.])

In [49]:
# 3rd equation
row = dimension - 3
x[row] = (augmat[row,dimension] 
          -augmat[row,dimension-1]*x[dimension-1] 
          -augmat[row,dimension-2]*x[dimension-2])/augmat[row, dimension-3]

In [50]:
x

array([ 0. , -6.5, 10. ,  5. ])

In [53]:
# 4th equation
row = dimension - 4
x[row] = (augmat[row,dimension] 
          -augmat[row,dimension-1]*x[dimension-1] 
          -augmat[row,dimension-2]*x[dimension-2]
          -augmat[row,dimension-3]*x[dimension-3])/augmat[row, dimension-3]

In [54]:
x

array([-3.5, -6.5, 10. ,  5. ])

Again, notice the pattern in the last few cells - they can be replaced with a loop too!