In [116]:
import numpy as np
np.set_printoptions(precision=2)

In [117]:
N = 4
matdim = (N, N+1)
augmat = np.array([[2,2,4,-2,10],[1,3,2,4,17],[3,1,3,1,18],[1,3,4,2,27]])

In [118]:
matdim

(4, 5)

In [119]:
augmat

array([[ 2,  2,  4, -2, 10],
       [ 1,  3,  2,  4, 17],
       [ 3,  1,  3,  1, 18],
       [ 1,  3,  4,  2, 27]])

In [120]:
prow = 0 #pivot row
for prow in range(0,N): #for each pivot row
    for row in range(prow+1, N): #for each row underneath the pivot row
        ratio = augmat[row, prow]/augmat[prow, prow] #find the ratio needed to gain 0 in the first position
        for col in range(prow, N+1): #for each element in current row
            augmat[row, col] -= ratio*augmat[prow,col] #M'_ij = M_ij-(R*M_kj) where N > j > k and N is the width of M
augmat

array([[ 2,  2,  4, -2, 10],
       [ 0,  2,  0,  5, 12],
       [ 0,  0, -3,  9, 15],
       [ 0,  0,  0,  4, 20]])

In [121]:
x = np.zeros(N)
x

array([0., 0., 0., 0.])

In [122]:
for i in reversed(range(0,N)): #for each element in x-vector, starting with the last
    sum=0
    for j in reversed(range(0,N)): #for each factor in the row
        if(i!=j): #exclude factor of itself
            sum += x[j]*augmat[i,j] #sum of other x-vector elements * factors
    x[i] = (augmat[i,N]-sum)/augmat[i,i]
sum

17.0

In [123]:
x

array([-3.5, -6.5, 10. ,  5. ])