In [80]:
import numpy as np
import csv
np.set_printoptions(precision=2)

In [81]:
i = 10
def y(i): #y-function
    return (2*i) + 0.3

def sig_x(i,n): #sum of x^n
    sum = 0
    for x in range(1,i+1):
        sum += x**n
    return sum


def sig_y(i,n): #sum of y^n
    sum = 0
    for x in range(1,i+1):
        sum += y(x)**n
    return sum


def sig_xy(i,n): #sum of (x^n)*y
    sum = 0
    for x in range(1,i+1):
        sum += y(x) * x**n
    return sum


def mean_y(i): #mean of y
    sum = 0
    for x in range(1,i+1):
        sum += y(x)
    return sum/i


def mean_x(i): #mean of x
    sum = 0
    for x in range(1,i+1):
        sum += x;
    return sum/i


#coefficient 1
def a1(i):
    return ((i*sig_xy(i,1))-(sig_x(i,1)*sig_y(i,1)))/((i*sig_x(i,2))-(sig_x(i,1))**2)


#coefficient 0
def a0(i):
    return mean_y(i)-(a1(i)*mean_x(i))


#correlation of x and y
def r(i):
    return ((i*sig_xy(i,1))-(sig_x(i,1)*sig_y(i,1)))/(np.sqrt((i*sig_x(i,2))-(sig_x(i,1))**2)*np.sqrt((i*sig_y(i,2))-(sig_y(i,1))**2))


In [82]:
def gauss_elim(N,augmat): #where N gives height
    matdim = (N, N+1)
    prow = 0 #pivot row
    x = np.zeros(N)
    
    for prow in range(0,N): #for each pivot row
        for row in range(prow+1, N): #for each row underneath the pivot row
            ratio = augmat[row, prow]/augmat[prow, prow] #find the ratio needed to gain 0 in the first position
            for col in range(prow, N+1): #for each element in current row
                augmat[row, col] -= ratio*augmat[prow,col] #M'_ij = M_ij-(R*M_kj) where N > j > k and N is the width of M
                
    for i in reversed(range(0,N)): #for each element in x-vector, starting with the last
        sum=0
        for j in reversed(range(0,N)): #for each factor in the row
            if(i!=j): #exclude factor of itself
                sum += x[j]*augmat[i,j] #sum of other x-vector elements * factors
        x[i] = (augmat[i,N]-sum)/augmat[i,i]
    return x
array = np.array([[2,2,4,-2,10],[1,3,2,4,17],[3,1,3,1,18],[1,3,4,2,27]])
gauss_elim(4,array)

array([-3.5, -6.5, 10. ,  5. ])

In [83]:
#open csv data
with open('data.csv', 'r') as f:
    r = csv.reader(f)
    data = list(r)
#create array containing values
val = np.array(data,dtype=float)

In [84]:
augmat = np.zeros([3,4])


In [85]:
""" Question Two """
#for the A matrix
def sum_x(x, n): #takes an x-value array and an index e.g. sum_x(val[:,0], diag)
    sum = 0
    for i in range(0,x.shape[0]):
        sum += x[i]**n
    return sum

def sum_xy(x, y, n): #takes an x-value array, y-value array and an index e.g. sum_y(val[:,0], val[:,1], diag)
    sum = 0
    for i in range(0, x.shape[0]):
        sum += y[i]*(x[i]**n)
    return sum

for diag in range(0,augmat.shape[0]+2): #for each +ve diagonal set (0 to 4)
    for htl in range(0, 3): #for the horizontal (0 to 2)
        for vtl in range(0, 3): #for the vertical (0 to 2)
            if htl+vtl == diag: #if (htl,vtl) lies on the +ve diagonal
                augmat[vtl,htl] = sum_x(val[:,0], diag) #set the element to sum

for i in range(0, 3): #for the b matrix
    augmat[i, 3] = sum_xy(val[:,0], val[:,1], i)

augmat

array([[ 2.30e+01,  0.00e+00,  8.36e+02, -1.60e+03],
       [ 0.00e+00,  8.36e+02,  0.00e+00,  8.46e+02],
       [ 8.36e+02,  0.00e+00,  5.46e+04, -1.07e+05]])

In [86]:
gauss_elim(augmat.shape[0], augmat)

array([ 3.48,  1.01, -2.  ])