In [1]:
import numpy as np
np.set_printoptions(precision=2)

In [2]:
N = 4
matdim = (N, N+1)
augmat = np.array([[2,2,4,-2,10],[1,3,2,4,17],[3,1,3,1,18],[1,3,4,2,27]])

In [3]:
matdim

(4, 5)

In [4]:
augmat

array([[ 2,  2,  4, -2, 10],
       [ 1,  3,  2,  4, 17],
       [ 3,  1,  3,  1, 18],
       [ 1,  3,  4,  2, 27]])

In [5]:
prow = 0 #pivot row
for prow in range(0,N): #for each pivot row
    for row in range(0, N): #for each row except for the pivot row
        if row!=prow:
            ratio = augmat[row, prow]/augmat[prow, prow] #find the ratio needed to gain 0 in the first position
            for col in range(prow, N+1): #for each element in current row
                augmat[row, col] -= ratio*augmat[prow,col] #M'_ij = M_ij-(R*M_kj) where N > j > k and N is the width of M
augmat

array([[  2,   0,   0,   0,  -7],
       [  0,   2,   0,   0, -13],
       [  0,   0,  -3,   0, -30],
       [  0,   0,   0,   4,  20]])

In [6]:
x = np.zeros(N)
x

array([0., 0., 0., 0.])

In [7]:
for i in reversed(range(0,N)): #for each element in x-vector, starting with the last
    for j in reversed(range(0,N)): #for each row
        x[i] = (1/augmat[i,i])*augmat[i,N]
sum

<function sum(iterable, /, start=0)>

In [8]:
x

array([-3.5, -6.5, 10. ,  5. ])